name: Simple Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup ssh hosts
        run: ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deleting github folder
        run: rm -rf .git

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Compress Project
        run: zip -r archive.zip build

      - name: Sync Project
        run: rsync -a --rsync-path="sudo rsync" archive.zip anubis@${{ secrets.HOST }}:/app/${{ github.event.repository.name }}/archive.zip

      - name: Remote Deploy
        run: |
          ssh -tt anubis@${{ secrets.HOST }} 'sudo -i -u root bash -c "
            cd /app/${{ github.event.repository.name }};
            unzip -u -o -q archive.zip;
          "'
